repos:
- hooks:
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: [--maxkb=10000]
  - id: check-executables-have-shebangs
  - id: detect-private-key
  repo: git@github.com:pre-commit/pre-commit-hooks.git
  rev: v3.2.0
